// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACjAXSkJjUI_hahalMADzrYCVa5B6Vs3g',
    appId: '1:929866734056:web:7429cf41730fabaad32c5d',
    messagingSenderId: '929866734056',
    projectId: 'untitle5-af95d',
    authDomain: 'untitle5-af95d.firebaseapp.com',
    storageBucket: 'untitle5-af95d.appspot.com',
    measurementId: 'G-P24FNM2LXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6pfQGL7dGdKrzfhAQEVJO09WUw-U3kPM',
    appId: '1:929866734056:android:04108aa83507cd24d32c5d',
    messagingSenderId: '929866734056',
    projectId: 'untitle5-af95d',
    storageBucket: 'untitle5-af95d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHjlGL-8aU6YEGXuyat0l9i1ndFtGT5Ns',
    appId: '1:929866734056:ios:bc0f6a96cf7fce5ad32c5d',
    messagingSenderId: '929866734056',
    projectId: 'untitle5-af95d',
    storageBucket: 'untitle5-af95d.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHjlGL-8aU6YEGXuyat0l9i1ndFtGT5Ns',
    appId: '1:929866734056:ios:bc0f6a96cf7fce5ad32c5d',
    messagingSenderId: '929866734056',
    projectId: 'untitle5-af95d',
    storageBucket: 'untitle5-af95d.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACjAXSkJjUI_hahalMADzrYCVa5B6Vs3g',
    appId: '1:929866734056:web:cce790cb21cc1fb7d32c5d',
    messagingSenderId: '929866734056',
    projectId: 'untitle5-af95d',
    authDomain: 'untitle5-af95d.firebaseapp.com',
    storageBucket: 'untitle5-af95d.appspot.com',
    measurementId: 'G-GJMS63LPVV',
  );

}